version: '3.8'

services:
  moonlight-web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moonlight-web.rule=Host(`moonlight.nooridev.com`)"
      - "traefik.http.routers.moonlight-web.entrypoints=web"
#      - "traefik.http.routers.moonlight-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.moonlight-web.loadbalancer.server.port=3000"

networks:
  traefik_default:
    external: true
